### ISSUE TITLE
 Error: ENOENT: no such file or directory, open '/admin/.next/server/app/api/proto/proto/schema.proto

### ISSUE THREAD

**Issue by yangjinhui** [milvus-io/milvus-sdk-node#276]
**Describe the bug:**
l am trying to use milvus in nextjs:14.0.4,when i use pnpm dev,it's ok,

but when i try to use pnpm build,then pnpm start,it give me a error message,
 Error: ENOENT: no such file or directory, open '/admin/.next/server/app/api/proto/proto/schema.proto.
my project directory structure is src/app/api/[methos]/route.ts

**Steps to reproduce:**

1.pnpm install @zilliz/milvus2-sdk-node
pnpm install copy-webpack-plugin
2.modify next.config.js

```
const path = require('path');
  const CopyWebpackPlugin = require('copy-webpack-plugin');
  
  /** @type {import('next').NextConfig} */
  const nextConfig = {
    webpack: (config, { isServer }) => {
      if (isServer) {
        // Copy the proto files to the server build directory
        config.plugins.push(
          new CopyWebpackPlugin({
            patterns: [
              {
                from: path.join(
                  __dirname,
                  'node_modules/@zilliz/milvus2-sdk-node/dist'
                ),
                to: path.join(__dirname, '.next'),
              },
            ],
          })
        );
      }
      // Important: return the modified config
      return config;
    },
  };
module.exports = nextConfig;
```

3.test script is

```
import { MilvusClient } from "@zilliz/milvus2-sdk-node";

import { NextRequest } from "next/server";

async function getData() {
  const milvusClient = new MilvusClient({
    // protoFilePath: {
    //   milvus:
    //     "/proto/proto/milvus.proto",
    //   schema:
    //     "/proto/proto/schema.proto",
    // },
    address: "192.168.1.5:19530",
    username: "root",
    password: "Milvus",
  });

  let res: any = await milvusClient.getMetric({
    request: { metric_type: "system_info" },
  });

  const result = res.response.nodes_info.map((v: any) => {
    return v.infos;
  });

  return result;
}

export async function POST(
  req: NextRequest,
  {
    params,
  }: {
    params: {
      action: "test";
    };
  }
) {
  if (params.action === "test") {
    const res = await getData();
    return Response.json(res);
  }
  return Response.json({ error: "Not Found" });
}
```

4.pnpm dev,it's correct

```
[
    {
        "has_error": false,
        "error_reason": "",
        "name": "querynode3",
        "hardware_infos": {
            "ip": "172.17.0.2:21123",
            "cpu_core_count": 4,
            "cpu_core_usage": 100,
            "memory": 8231878656,
            "memory_usage": 225267712,
            "disk": 104857600,
            "disk_usage": 2097152
        },
        "system_info": {
....
```

4.pnpm build& pnpm start,a error has occurred

` ⨯ Error: ENOENT: no such file or directory, open '/Users/normanyang/Documents/workspace/nextjs/dam/admin/.next/server/app/api/proto/proto/schema.proto'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:457:35)`

As you can see,i try to specify the address of proto.It's not useful either

**Milvus-node-sdk version:**
2.3.5
**Milvus version:**
2.3.5

**Comment by zhanshuyou** [comment]
You can try Next.js 14.0.1, we are fixing the issue.

**Comment by zhanshuyou** [comment]
You can try this
![image](https://github.com/milvus-io/milvus-sdk-node/assets/7420640/041664fd-1de8-45eb-99b2-7cf172379f62)
https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config?source=post_page-----f3c51de2fe1d--------------------------------

**Comment by yangjinhui** [comment]
> You can try Next.js 14.0.1, we are fixing the issue.

Hi,I tried this version and the same error occurred.

**Comment by yangjinhui** [comment]
> You can try this ![image](https://private-user-images.githubusercontent.com/7420640/301482841-041664fd-1de8-45eb-99b2-7cf172379f62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzM1NzUsIm5iZiI6MTcwODY3MzI3NSwicGF0aCI6Ii83NDIwNjQwLzMwMTQ4Mjg0MS0wNDE2NjRmZC0xZGU4LTQ1ZWItOTliMi03Y2YxNzIzNzlmNjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjNUMDcyNzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWQwYjc3MjNkYWM1NDA2ZGFkYzFmN2QwMmM0MWU1N2VmNTBkMmZiNmE1NjVkZWU4ZDM3NmJlZTc0NzVmZDllNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MZTHcEp1vTjBlZTBH8HjwecwSkYdY6X4EAu2KpdD8LE) https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config?source=post_page-----f3c51de2fe1d--------------------------------

Hi,which file should I add this to? I tried to add this into my test script,but the error is still exists.

**Comment by zhanshuyou** [comment]
I add this to page.tsx
You can try this example
https://github.com/milvus-io/milvus-sdk-node/tree/main/examples/nextjs

**Comment by yangjinhui** [comment]
> @yangjinhui I add this to page.tsx You can try this example https://github.com/milvus-io/milvus-sdk-node/tree/main/examples/nextjs

I just tried, dev is correct,but the build&start still reported an error.
"""
Error: Unable to load service: milvus.proto.milvus.MilvusService from /Users/normanyang/Downloads/milvus-sdk-node-main 2/examples/nextjs/.next/proto/proto/milvus.proto
    at u (/Users/normanyang/Downloads/milvus-sdk-node-main 2/examples/nextjs/.next/server/app/page.js:35:80587)
    at a.connect (/Users/normanyang/Downloads/milvus-sdk-node-main 2/examples/nextjs/.next/server/app/page.js:35:52165)
    at new a (/Users/normanyang/Downloads/milvus-sdk-node-main 2/examples/nextjs/.next/server/app/page.js:35:13366)
    at o (/Users/normanyang/Downloads/milvus-sdk-node-main 2/examples/nextjs/.next/server/app/page.js:1:3786)
    at a (/Users/normanyang/Downloads/milvus-sdk-node-main 2/examples/nextjs/.next/server/app/page.js:1:3968)
    at em (/Users/normanyang/Downloads/milvus-sdk-node-main 2/examples/nextjs/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131226)
    at /Users/normanyang/Downloads/milvus-sdk-node-main 2/examples/nextjs/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142926
    at Array.toJSON (/Users/normanyang/Downloads/milvus-sdk-node-main 2/examples/nextjs/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146504)
    at stringify (<anonymous>)
    at eR (/Users/normanyang/Downloads/milvus-sdk-node-main 2/examples/nextjs/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134889)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '917872557'
}
"""

**Comment by zhanshuyou** [comment]
@yangjinhui 
I have reproduced this error. I will check the code.
I will notify you once it's resolved

**Comment by zhanshuyou** [comment]
@yangjinhui
I have fixed this issue by page api router
Details: https://github.com/milvus-io/milvus-sdk-node/pull/280/files

**Comment by yangjinhui** [comment]
> @yangjinhui I have fixed this issue by page api router Details: https://github.com/milvus-io/milvus-sdk-node/pull/280/files

I will try,thanks a lot.

**Comment by shanghaikid** [comment]
https://github.com/milvus-io/milvus-sdk-node/tree/main/examples/nextjs 

Readme upgraded, close the issue.

**Comment by c121914yu** [comment]
This problem still occurs under the nextjs14.2 page router：

```
 no such file or directory, open 'xxxx/projects/app/.next/proto/proto/schema.proto'
```

I'm using the monorepo structure，related configurations have been added:

![image](https://github.com/milvus-io/milvus-sdk-node/assets/50446880/1f13a168-1d52-41be-86ef-410a1d9f58ab)

**Comment by shanghaikid** [comment]
> This problem still occurs under the nextjs14.2 page router：
> 
> ```
>  no such file or directory, open 'xxxx/projects/app/.next/proto/proto/schema.proto'
> ```
> 
> I'm using the monorepo structure，related configurations have been added:
> 
> ![image](https://private-user-images.githubusercontent.com/50446880/334680099-1f13a168-1d52-41be-86ef-410a1d9f58ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjQwODYsIm5iZiI6MTcxNjk2Mzc4NiwicGF0aCI6Ii81MDQ0Njg4MC8zMzQ2ODAwOTktMWYxM2ExNjgtMWQ1Mi00MWJlLTg2ZWYtNDEwYTFkOWY1OGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA2MjMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZmY4MWRhYjI2YmUxN2ZkMGVlNjk3NmI4ZmIxMjFjZTNkOTNkYWViYmU0YjU3MmJiMTc1ZDU3OTdhYzdhODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KQ7RfpJ5ZI1hn5FgpzkmiE0shC_bb2Krz02Q_ebCEWE)

@zhanshuyou any idea

**Comment by c121914yu** [comment]
> 在nextjs14.2页面路由器下还是会出现这个问题：
> 
> ```
>  no such file or directory, open 'xxxx/projects/app/.next/proto/proto/schema.proto'
> ```
> 
> 我使用的是monorepo结构，sdk安装在其中一个子包中。next.config.json 已添加：
> 
> ![图像](https://private-user-images.githubusercontent.com/50446880/334680099-1f13a168-1d52-41be-86ef-410a1d9f58ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzYyODYsIm5iZiI6MTcxNjk3NTk4NiwicGF0aCI6Ii81MDQ0Njg4MC8zMzQ2ODAwOTktMWYxM2ExNjgtMWQ1Mi00MWJlLTg2ZWYtNDEwYTFkOWY1OGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA5NDYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2Yjk2ODFlNGRkZjljOTMzOGQ2ZGE3ZDQ2ODM1MGZiZThhMWZkMmI1OTZjMTJkYTVhZWRkYzFkZTZhY2IyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j350nvh0-2t5IXuiTKYe08-O94Bfre1MNZSD3fOVPd0)

This configuration of nextjs is invalid due to a monorepo problem. It can manually add webpack configuration to solve the problem.
```
config.externals.push('@zilliz/milvus2-sdk-node');
```
