### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/var/task/.next/proto/proto/schema.proto'

### ISSUE THREAD

**Issue by AOvardovVSG** [milvus-io/milvus-sdk-node#326]
**Describe the bug:**
I'm trying to use Milvus with Langchain in a Next.js app. I finished my project and tested it locally, and it works perfectly without any issues. However, when it came time to deploy my project to Vercel, I ran into an issue with the production version.

When I try to use Milvus vector store for similarity searching, I receive this error:
ENOENT: no such file or directory, open '/var/task/.next/proto/proto/schema.proto'.

I have tried a couple of things to fix it but without success:

**First, I tried to add this code into my next.config.js**
```
experimental: {
    serverComponentsExternalPackages: ['@zilliz/milvus2-sdk-node'],
}

```

Second, I tried to copy proto files into the .next folder:
```
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
  webpack: (config, { isServer }) => {
    if (isServer) {
      const dirname = path.resolve(path.dirname(''));

      // Copy the proto files to the server build directory
      config.plugins.push(
        new CopyWebpackPlugin({
          patterns: [
            {
              from: path.join(dirname, 'node_modules/@zilliz/milvus2-sdk-node/dist'),
              to: path.join(dirname, '.next'),
            },
          ],
        })
      );
    }
    // Important: return the modified config
    return config;
  },
};
```

Despite these efforts, I haven't been able to resolve the issue.

This is the way of how I'm using Milvus
```
import { Milvus } from "@langchain/community/vectorstores/milvus";

export const getVectorStore = async () => {
  const embeddings = getEmbeddings();

  return Milvus.fromExistingCollection(embeddings, {
    collectionName: process.env.MILVUS_COLLECTION_NAME,
    url: process.env.MILVUS_DB_URL,
    clientConfig: { address: '', token: process.env.MILVUS_API_KEY }
  });
}

const vectorStore = await getVectorStore();
const res = await vectorStore.similaritySearch('question')
```

**Steps to reproduce:**

1. Deploy app to vercel

**Milvus-node-sdk version:**
**@zilliz/milvus2-sdk-node: 2.4.2
next 14.1.4**

**Milvus version:**

**Comment by zhanshuyou** [comment]
@AOvardovVSG 
You can try this example https://github.com/zhanshuyou/milvus-next-example
Deploy to vercel successfully
![image](https://github.com/milvus-io/milvus-sdk-node/assets/7420640/14cde152-64b4-49da-b6ed-95fff28f28e0)
If there are still problems, please provide an example repository.

**Comment by AOvardovVSG** [comment]
Hi @zhanshuyou,

Thank you for your example. While it is helpful, my situation is slightly different. I am working on a client-side component called Form that includes a basic form element with an input field for a question and a submit button. When the form is submitted, it sends a POST request containing the question's value to an endpoint in my Next.js application (located in the api folder).

This endpoint is responsible for searching documents in a vector store within an existing Milvus collection. Unfortunately, due to company policy, I am unable to share the repository.

Here is the code for my Next.js endpoint:
It is located in "api/documents/route.ts" path.

```
import { NextResponse } from "next/server";
import { HuggingFaceInferenceEmbeddings } from "@langchain/community/embeddings/hf";
import { Milvus } from "@langchain/community/vectorstores/milvus";

export async function POST(req: Request) {
  try {
    const embeddings = new HuggingFaceInferenceEmbeddings({ apiKey: process.env.HUGGINGFACEHUB_API_KEY });

    const vectorStore = await Milvus.fromExistingCollection(embeddings, {
      collectionName: process.env.MILVUS_COLLECTION_NAME,
      url: process.env.MILVUS_DB_URL,
      clientConfig: { address: '', token: process.env.MILVUS_API_KEY }
    });

    const res = await vectorStore.similaritySearch('Why the sky is blue?');

    return NextResponse.json({ res: res }, { status: 200 });
  } catch (error: Error | any) {
    return NextResponse.json({ error: error.message }, { status: error.status ?? 500 });
  }
}
```

And actually I received this error only inside next.js endpoint. Everything works fine in a server-side component, but I have to do that in the endpoint because we use the result from the search for other purposes and it has to be in an endpoint.

**That's the issue that I receive** 
**ENOENT: no such file or directory, open '/var/task/node_modules/@zilliz/milvus2-sdk-node/dist/proto/proto/common.proto'**


**Please take in notes that I copied your next.config.js and also included the proto files in the public folder as from your example.**

Thanks in advance! I hope that you will find a way to reproduce and fix that.

**Comment by zhanshuyou** [comment]
I have already moved it to the /api folder, and it still works properly.
https://github.com/zhanshuyou/milvus-next-example/blob/main/app/api/langchain/route.ts

**Comment by AOvardovVSG** [comment]
Hi @zhanshuyou ,

Thank you again for your solution! I have identified the root cause of the issue. When I make a GET request, everything works fine. However, when I make a POST request, I encounter an error.

It seems the issue might be related to how Next.js handles and structures files when creating a POST function.

You can reproduce the error by changing your method to POST.

**Comment by zhanshuyou** [comment]
> Hi @zhanshuyou ,
> 
> Thank you again for your solution! I have identified the root cause of the issue. When I make a GET request, everything works fine. However, when I make a POST request, I encounter an error.
> 
> It seems the issue might be related to how Next.js handles and structures files when creating a POST function.
> 
> You can reproduce the error by changing your method to POST.

I have already reproduced it.

**Comment by shanghaikid** [comment]
What is your next.js version?

**Comment by AOvardovVSG** [comment]
> What is your next.js version?

14.1.4

**Comment by shanghaikid** [comment]
> > What is your next.js version?
> 
> 14.1.4

Hi, can you try this config? 

https://github.com/zilliztech/zilliz-cloud-typescript-example/blob/master/semantic-search-example/next.config.js

**Comment by kknono** [comment]
Additionally, modifying it in Nuxt 3 can work very well:

hooks: {

    'nitro:build:public-assets': (_nitro: any) => {
      
      const sourceDir = path.resolve(__dirname, 'node_modules/@zilliz/milvus2-sdk-node/dist/proto')
      const destDir = path.resolve(__dirname, '.output/server/node_modules/@zilliz/milvus2-sdk-node/dist/proto')

     
      const copyDir = (src: string, dest: string): void => {
        if (!fs.existsSync(dest)) {
          fs.mkdirSync(dest, { recursive: true })
        }
        fs.readdirSync(src).forEach((file) => {
          const srcFile = path.resolve(src, file)
          const destFile = path.resolve(dest, file)
          if (fs.lstatSync(srcFile).isDirectory()) {
            copyDir(srcFile, destFile)
          }
          else {
            fs.copyFileSync(srcFile, destFile)
          }
        })
      }
 
      copyDir(sourceDir, destDir)
      console.log('Proto files copied successfully!')
    },
  },

**Comment by AryanKuAg** [comment]
> @AOvardovVSG You can try this example https://github.com/zhanshuyou/milvus-next-example Deploy to vercel successfully ![image](https://private-user-images.githubusercontent.com/7420640/341321717-14cde152-64b4-49da-b6ed-95fff28f28e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjkxNDQsIm5iZiI6MTcyNzI2ODg0NCwicGF0aCI6Ii83NDIwNjQwLzM0MTMyMTcxNy0xNGNkZTE1Mi02NGI0LTQ5ZGEtYjZlZC05NWZmZjI4ZjI4ZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjVUMTI1NDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODFjZGEwZTFhYjUzYzA3YTg1OGU2MWIyZDZiMDRiNmU2Y2Y2Njg3NmQxOWY4ODA3OGJlNjlmOWQxMTc2NDQzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QU1MsZcYC3zsb7bX4IK-2JsQ2wq_Q0y2307R-mhMKYM) If there are still problems, please provide an example repository.

Thanks I was facing this issue for like a week, this is now resolved, thanks a lot guys 🙏

**Comment by zhanshuyou** [comment]
@AryanKuAg 
Have a try
https://github.com/zilliztech/zilliz-cloud-typescript-example/blob/master/semantic-search-example/next.config.js

**Comment by tangkunyin** [comment]
> Hi @zhanshuyou ,
> 
> Thank you again for your solution! I have identified the root cause of the issue. When I make a GET request, everything works fine. However, when I make a POST request, I encounter an error.
> 
> It seems the issue might be related to how Next.js handles and structures files when creating a POST function.
> 
> You can reproduce the error by changing your method to POST.

I tried to get the reasons why, and the problems were: 

- **Server-Side Dependencies:** Next.js optimizes for client-side code and excludes unnecessary server-side dependencies by default. When you’re working with something like Milvus, which relies on .proto files and low-level libraries, these aren’t automatically bundled unless specified.

- **Deployment:** Services like Vercel require you to explicitly specify any external files or libraries that are not part of the standard Next.js output tracing. Without this configuration, the API may fail at runtime due to missing files.

**Comment by jkvim** [comment]
Note for anyone use pnpm but still failed, we could try add `yarn.lock`

**Comment by shanghaikid** [comment]
> Note for anyone use pnpm but still failed, you could try add `yarn.lock`

New version will be released soon, we are able to get rid of these proto files soon.
